= System Specification - Rocketman
Hain Lukas, Plakolb Marcel, Kaufmann Jan
1.8.0, 2020-10-28
icon:home[link="https://htl-leonding-project.github.io/rocketman/"]

//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
//icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/asciidoctor-docker-template/master/asciidocs/{docname}.adoc] ‏ ‏ ‎
//icon:github-square[link=https://github.com/htl-leonding-college/asciidoctor-docker-template] ‏ ‏ ‎
//icon:home[link=https://htl-leonding.github.io/]
endif::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== System Specification

=== Initial situation
The HTL Leonding is a HTL in the central region of Upper Austria. Groups of students often take part in the CanSat competition where the goal is to shoot a satellite the size of a tin can at a height of 500 meters.

=== Actual state
This satellite is equipped with various sensors and sends telemetry data (sensor data such as ambient temperature, altitude, etc.) to one or more ground stations.

=== Problem definition
The participating students currently do not have a uniform, easily transportable way to control a rocket or the satellite and to receive or record telemetry data (see actual state). Launching device and control unit are currently not connected to each other. The Launching device is currently a small handheld, connected by wire to a small electronic detonator inside the rocket. https://www.ebay.de/itm/Quest-Zuendgeraet-fuer-Modellraketen-mit-Blinklicht-und-Piepser-Neu-OVP-/193723804904[Ebay link]. Each student group always has its own non-unified design.

=== Task definition
Based on an externally delivered control unit, software for the implementation on the problem statement given above will be delivered by the project team. The results which will be described in this section are divided into the prerequisites, the functionality and other aspects which derive from the functionality, each in a separate subsection.

==== Prerequisites
In the following requirements we assume that the hardwareparts are delivered externally.
Moreover we assume that all delivered software APIs come together with the documentation.

==== Functional requirements
* The user should be able to set the software mode of operation
** The trigger for the change of software mode is the delivered suitcase key
** The software should be able to chose between user-mode, readonly-mode and admin-mode by the movement of the suitcase key
*** readonly-mode: In this mode it should only be possible to observe telemetry data
*** user-mode: In this mode it should be possible to observe telemetry data, initiate the countdown and control an actuator
*** admin-mode: In this mode the system may be configured(e.g. set the Countdown and activate an actuator)
* The software in user-mode should be able to initiate the ignition of the rocket
** The ignition should be possible by wire or wirelessly
* Communication capabilities should be delivered
** The suitcase should be able to communicate by standard API with competition administration system. The standard API documentation must be delivered by the competition administration.
* It should be possible to communicate wirelessly with several branch offices simultaneously.


==== Non-functional requirements
* Easy usability
** Due to user with limited software knowledge the UI has to be easy to use
* Ignition current may only flow, if this is really wanted by the user
* The control unit should function without internet or cloud access
** As currently known the internet access is only required for downloading settings for the launch, so the user has to download them beforehand

==== Class-Diagram
[plantuml,classdiagram, png]
----
@startuml
class CanSatConfiguration{
    String name
    int countdown
    int igniter
    String resistance
    boolean useJoyStick
    boolean useVideo
}
class DataSet{
    Long id
    String description
    String value
    String unit
    LocalDateTime timestamp
    Long Startid
}
class Start{
    Long id
    String comment
    LocalDateTime startDate
    LocalDateTime endDate
}

Start "1" -right- "*" DataSet
@enduml
----

==== ERD
[plantuml,erd, png]
----
@startuml
class DataSet{
    ds_id: number <<generated>>
    --
    ds_description: varchar
    ds_value: varchar
    ds_unit: varchar
    ds_timestamp: date
    --
    ds_st_id: number <<FK>>
}
class Start{
    st_id: number <<generated>>
    --
    st_comment: varchar
    st_startDate: Date
    st_endDate: Date
}

Start ||-right-|{ DataSet
@enduml
----

==== Use-Case-Diagramm
[plantuml,usecasediagramm, png]
----
@startuml
skinparam actorStyle awesome
left to right direction
:UserGUI:
:AdminGUI:
:ReadOnlyUserGUI:
rectangle Rocketman {
    (receive and save telemetry data)
    rectangle {
        (control actuator)
        (communicate wirelessly with branch offices)
        (set software mode of operation)
    }
    rectangle {
        (receive and save configurations)
        (activate actuator)
        (set countdown)
        (receive and save configurations) .right.> (activate actuator)
        (receive and save configurations) .left.> (set countdown)
    }
}
ReadOnlyUserGUI -- (receive and save telemetry data)
UserGUI -->> ReadOnlyUserGUI
UserGUI -- (control actuator)
UserGUI -- (set software mode of operation)
UserGUI -- (communicate wirelessly with branch offices)
AdminGUI -->> UserGUI
AdminGUI -- (receive and save configurations)
@enduml
----


=== Goals
The goal is to make it easier for future students to participate. As there is already an existing design for the ground station.

=== Quantity structure
Currently not foreseeable. Will be added as soon as possible.

== Concept
=== System architecture
[plantuml, systemarchitecture, png]
----
package "Raspberry Pi" {
    database "LocalDB" as db {
    }
    node "Quarkus" as q {
        [REST] as r
    }
    file "Config File" as conf
    file "Exported Data" as export
    component "MQTT Broker" as mqtt
    component "Key switch" as key
    component "Joystick" as joy
}

db - q
r -do- conf
mqtt -up- q
joy -up- mqtt
key -up- mqtt
q -do- export

package CanSat {
    node "Sensors" as s {
        [Humidity Sensor]
        [Temperatur Sensor]
    }
    node "Actuator" as a {
        [Steering]
        [Camera]
    }
}

mqtt -- s
mqtt -- a
----
