# This is a basic workflow to help you get started with Actions

name: Publish Rocketman Frontend and Backend

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: ['master']

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_backend:
    name: Build backend
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: rocketman-backend
    defaults:
      run:
        working-directory: ./prototypes/mqtt-backend
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Package
        run: mvn package -DskipTests
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: docker build . -f src/main/docker/Dockerfile.fast-jar --tag $IMAGE_NAME
        with:
          arch: aarch64
          distro: ubuntu20.04
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
  build_frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: rocketman-frontend
    defaults:
      run:
        working-directory: ./prototypes/frontend-angular/rocketman
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: docker build . --tag $IMAGE_NAME
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
  build_backend_aarch64:
    name: Build backend aarch64
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: rocketman-backend-aarch64
    defaults:
      run:
        working-directory: ./prototypes/mqtt-backend
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Package
        run: mvn package -DskipTests
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: uraimo/run-on-arch-action@v2.1.1
        with:
          arch: aarch64
          distro: ubuntu20.04
          run: docker build . -f src/main/docker/Dockerfile.fast-jar --tag $IMAGE_NAME
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  build_frontend_aarch64:
    name: Build frontend aarch64
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: rocketman-frontend-aarch64
    defaults:
      run:
        working-directory: ./prototypes/frontend-angular/rocketman
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Packages
        uses: uraimo/run-on-arch-action@v2.1.1
        with:
          arch: aarch64
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          run: |
            echo "Building Image"
            docker build . --tag rocketman-frontend-aarch64
            echo "Publishing Image"
            IMAGE_ID=ghcr.io/${{ github.repository_owner }}/rocketman-frontend-aarch64
            IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
            VERSION=latest
            echo IMAGE_ID=$IMAGE_ID
            echo VERSION=$VERSION
            docker tag rocketman-frontend-aarch64 $IMAGE_ID:$VERSION
            docker push $IMAGE_ID:$VERSION
